In [1]:
import pandas as pd 

df = pd.read_csv("appartements.csv")

df[["quartier","prix"]]

   quartier   prix
0    Centre  180.0
1    Centre  255.0
2    Centre  340.0
3    Centre  460.0
4      Gare  150.0
5      Gare  205.0
6      Gare  280.0
7      Gare  370.0
8      Nord  140.0
9      Nord  185.0
10     Nord  250.0
11     Nord  345.0
12      Sud  160.0
13      Sud  240.0
14      Sud    NaN
15      Sud  470.0
16      Sud  470.0

In [2]:
df[df["quartier"]== "Nord"]

    id quartier  surface  pieces   prix  etage
8    9     Nord       40       2  140.0    1.0
9   10     Nord       55       2  185.0    3.0
10  11     Nord       75       3  250.0    0.0
11  12     Nord      110       5  345.0    2.0

In [3]:
df[(df["surface"] > 70) & (df["prix"] < 400)]

    id quartier  surface  pieces   prix  etage
7    8     Gare       95       4  370.0    NaN
10  11     Nord       75       3  250.0    0.0
11  12     Nord      110       5  345.0    2.0

In [4]:
df[df["quartier"].isin(["Centre","Gare"]) & (df["pieces"]>=3)]

   id quartier  surface  pieces   prix  etage
2   3   Centre       62       3  340.0    4.0
3   4   Centre       85       4  460.0    2.0
6   7     Gare       70       3  280.0    1.0
7   8     Gare       95       4  370.0    NaN

In [5]:
print(df.loc[2:4,["surface","prix"]])
df.iloc[2:4]

   surface   prix
2       62  340.0
3       85  460.0
4       35  150.0

   id quartier  surface  pieces   prix  etage
2   3   Centre       62       3  340.0    4.0
3   4   Centre       85       4  460.0    2.0